### ISSUE TITLE
bouw css geeft errors

### ISSUE THREAD

**Issue by mehmeterdemsoy** [dso-toolkit/dso-toolkit#1832]
Sw-behandelen geeft tijdens bouwen volgende errors:

13 rules skipped due to selector errors:oad:flatten Completed in 1ms
  .banner .row>div>.dso-rich-content h1+p+* -> Cannot read properties of undefined (reading 'type')
  .banner .row>div>.dso-rich-content h2+p+* -> Cannot read properties of undefined (reading 'type')
  .banner .row>div>.dso-rich-content h3+p+* -> Cannot read properties of undefined (reading 'type')
  .banner .row>div>.dso-rich-content h4+p+* -> Cannot read properties of undefined (reading 'type')
  .banner .row>div>.dso-rich-content h5+p+* -> Cannot read properties of undefined (reading 'type')
  .banner .row>div>.dso-rich-content h6+p+* -> Cannot read properties of undefined (reading 'type')
  .dso-banner:not(.row) .row>div>.dso-rich-content h1+p+* -> Cannot read properties of undefined (reading 'type')
  .dso-banner:not(.row) .row>div>.dso-rich-content h2+p+* -> Cannot read properties of undefined (reading 'type')
  .dso-banner:not(.row) .row>div>.dso-rich-content h3+p+* -> Cannot read properties of undefined (reading 'type')
  .dso-banner:not(.row) .row>div>.dso-rich-content h4+p+* -> Cannot read properties of undefined (reading 'type')
  .dso-banner:not(.row) .row>div>.dso-rich-content h5+p+* -> Cannot read properties of undefined (reading 'type')
  .dso-banner:not(.row) .row>div>.dso-rich-content h6+p+* -> Cannot read properties of undefined (reading 'type')
  .form-horizontal .form-group.dso-static .dso-field-container *+* -> Cannot read properties of undefined (reading 'type')

------------
mogelijk oorzaak:
In de code packages/sources/src/components/banner/banner.scss:

```css
        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
          color: $zwart;
          font-size: 1rem;
          line-height: $line-height-base;
          margin-bottom: 0;

          + p {
            display: inline;

            + * {
              margin-top: $u2;
            }
          }
        }
```

wordt $u2 niet gezet lijkt het.
