### ISSUE TITLE
Form: Documentatie legacy van fractal

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1894]
- [x] `form.css-template.ts` voorzien van `formButtonsTemplate()`, zie versie <=46 op dso-toolkit.nl voor voorbeeld
- [x] Voorbeeldpagina maken met oude Fractal context.
- [x] Form Buttons documentatie maken.

## Form voorbeeldpagina (data)

```yml
status: ready
default: form-vertical
context:
  __title: form vertical
  fieldsets:
  - legend: Contact
    groups:
    - id: voornaam
      inputType: input
      type: text
      label: Voornaam
      required: true
    - id: achternaam
      inputType: input
      type: text
      label: Achternaam
      helpText: Mag ook de familienaam zijn
    - inputType: static
      label: Geslacht
      value: Man
    - id: geboortedatum
      inputType: input
      type: text
      label: Geboortedatum
      inputIcon: calendar
    - id: email
      inputType: input
      type: email
      label: E-mailadres
      required: true
    - id: password
      inputType: input
      type: text
      label: Wachtwoord
    - id: password_bevestig
      inputType: input
      type: text
      label: Wachtwoord (bevestig)
    - id: nieuwsbrief
      inputType: confirm
      label: Stuur mij de maandelijkse nieuwsbrief
      helpText: Uw gegevens zullen niet worden gedeeld met derden
  - legend: Bijlagen
    groups:
      - id: documenten
        inputType: files
        description: Geef een tekening van de nieuwe situatie in 1:100. Een situatietekening geeft een schets van de bestaande en de nieuwe situatie met daarop duidelijk de maatvoering en de schaalaanduiding (1:100).
        buttonClass: secondary
        files:
          - filename: Schetsen_en_foto's_1.pdf
          - filename: Bijlagen_hoveniersbedrijf_de_heggeschaar_hoveniers.jpg
            confidential: true
  - legend: Beleg
    groups:
    - id: beleg
      inputType: select
      label: Beleg
      multiple: true
      options:
      - optionType: Vlees
        items:
        - value: worst
          label: Worst
        - value: salami
          label: Salami
        - value: geit
          label: Geit
      - optionType: Vis
        items:
        - value: zalm
          label: Zalm
        - value: makreel
          label: Makreel
  - legend: Auto merk
    groups:
    - id: auto_merk
      inputType: select
      label: Type auto
      options:
      - optionType: Europees
        items:
        - value: alfa
          label: Alfa Romeo
        - value: fiat
          label: Fiat
        - value: mercedes
          label: Mercedes
          selected: true
        - value: volkswagen
          label: Volkswagen
  - legend: Filter op type
    groups:
    - id: filter_type
      inputType: search-bar
      label: Type
      searchBar:
        placeholder: Bv. GTI
        icon: true
        id: filter_type
        hideSearchButton: true
        clearButton: true
  - legend: Aanhanger
    groups:
    - id: aanhanger
      inputType: radios
      label: Welke aanhanger
      options:
      - value: bak
        label: Bak
      - value: caravan
        label: Caravan
        checked: true
      - value: fietsendrager
        label: Fietsendrager
      - value: oplegger
        label: Oplegger
    - id: input-checkbox
      inputType: checkboxes
      label: Maak een keuze
      options:
      - value: 1
        label: een
        id: checkbox_1
      - value: 2
        label: twee
        id: checkbox_2
      - value: 3
        label: drie
        id: checkbox_3
    - id: input-number-voorbeeld
      inputType: input-number
      label: Aantal
      count: 0
  - legend: Vraag
    groups:
    - id: gekke_vraag
      inputType: textarea
      rows: 5
      label: Waarom heeft een tankstation dat 24 uur per dag open is een slot op de deur?
      helpText: Deze vraag heeft een toelichting
  - legend: Vraag met infobutton
    groups:
    - id: input-radio-infobutton
      inputType: radios
      label: Soms laat de vraagstelling aan duidelijkheid te wensen over. Wenst u een toelichting hierop?
      options:
      - value: 1
        label: ja, de vraagstelling aan duidelijkheid te wensen over, ik wil graag een toelichting hierop
        checked: true
        infoOpen: false
        infoButtonLabel: Toelichting bij antwoord
        infoText: |
          Empty
      - value: 2
        label: nee, het is mij duidelijk
      infoOpen: false
      infoButtonLabel: Toelichting bij vraag
      infoText: |
        Empty
  - legend: Vraag met toelichting uitgeklapt
    groups:
    - id: input-radio-infobutton-open
      inputType: radios
      label: Toelichting op uw vraag
      options:
      - value: 1
        label: ja
        checked: true
        infoOpen: false
        infoButtonLabel: Toelichting bij antwoord
        infoText: Empty
      - value: 2
        label: nee
      infoOpen: true
      infoButtonLabel: Toelichting op uw vraag
      infoText: |
        <h4>Toelichting bij vraag: "Toelichting op uw vraag"</h4>
        <p>Bij verticale formulieren wordt het bij checkboxen en radio's onoverzichtelijk als de toelichting bij de vraag EN opties toont</p>
  buttons:
  - type: button
    modifier: dso-tertiary
    label: Annuleren
  - type: submit
    modifier: dso-primary
    label: Verstuur
variants:
- name: form-horizontal
  context:
    __title: form horizontal
    formModifier: form-horizontal
- name: multi-page
  context:
    __title: multipage form
    fieldsets:
    - legend: Contact
      groups:
      - id: voornaam
        inputType: input
        type: text
        label: Voornaam
        required: true
    asideButtons:
    - type: button
      modifier: dso-tertiary
      label: Vorige stap
      icon: angle-left
    buttons:
    - type: button
      modifier: dso-tertiary
      label: Secondaire actie
    - type: submit
      modifier: dso-primary
      label: Volgende stap
      iconAfter: angle-right
- name: sections
  context:
    __title: form with sections
    fieldsets:
    - legend: Contact
      groups:
      - id: voornaam
        inputType: input
        type: text
        label: Voornaam
        required: true
    buttons:
    - type: button
      modifier: dso-tertiary
      label: Secondaire actie
    - type: submit
      modifier: dso-primary
      label: Primaire actie
- name: single-page
  context:
    __title: single page form
    formModifier: dso-single-page
    fieldsets:
    - legend: Invoervelden
      groups:
      - id: invoer-veld-1
        inputType: input
        type: text
        label: Voornaam
      - id: invoer-veld-2
        inputType: input
        type: text
        label: Achternaam
    buttons:
    - type: submit
      modifier: dso-primary
      label: Primaire actie
    - type: button
      modifier: dso-tertiary
      label: Secondaire actie
- name: autocomplete
  context:
    __title: form met autocomplete
    __explanation: Het HTML autocomplete-attribuut wordt gebruikt om aan te geven of het invoerveld door de browser automatisch, en met welke waarde, ingevuld kan worden.
    formModifier: dso-single-page
    fieldsets:
    - legend: Invoervelden
      groups:
      - id: voornaam
        inputType: input
        type: text
        label: Voornaam
        autocomplete: given-name
      - id: achternaam
        inputType: input
        type: text
        label: Achternaam
        autocomplete: family-name
      - id: straat
        inputType: input
        type: text
        label: Straat
        autocomplete: address-line1
      - id: huisnummer
        inputType: input
        type: text
        label: Huisnummer (plus letter en toevoeging)
        autocomplete: address-line2
      - id: postcode
        inputType: input
        type: text
        label: Postcode
        autocomplete: postal-code
      - id: woonplaats
        inputType: input
        type: text
        label: Woonplaats
        autocomplete: address-level2
      - id: telefoon
        inputType: input
        type: tel
        label: Telefoon
        autocomplete: tel
      - id: email
        inputType: input
        type: email
        label: Email adres
        autocomplete: e-mail
      - id: land
        inputType: select
        label: Land
        autocomplete: country
        options:
          - value: nl
            label: Nederland
          - value: be
            label: Belgie
          - value: de
            label: Duitsland
    buttons:
    - type: submit
      modifier: dso-primary
      label: Primaire actie
    - type: button
      modifier: dso-tertiary
      label: Secondaire actie
- name: simple-form
  context:
    __title: Simpel form
    __explanation: Een formulier waar <code>.form-group</code> direct in <code>&lt;form&gt;</code> staat.
    formModifier: form-horizontal
    fieldsets:
    - groups:
      - id: plat-dak
        label: Heeft de dakkapel een plat dak?
        inputType: radios
        inline: true
        options:
          - value: '1'
            label: Ja
          - value: '0'
            label: Nee
      - id: afstand
        label: Wat is de afstand tussen de zijkanten van de dakkapel en de zijranden van het dak?
        inputType: checkboxes
        options:
        - id: minder
          label: 50 cm of minder
        - id: meer
          label: meer dan 50 cm
    buttons:
    - type: submit
      modifier: dso-primary
      label: Volgende
- name: header-in-legend
  context:
    __title: header in legend
    formModifier: dso-header-in-legend
    fieldsets:
    - legend: <h1>Heading H1</h1>
      groups:
      - id: invoer-veld-1
        inputType: input
        type: text
        label: Voornaam
      - id: invoer-veld-2
        inputType: input
        type: text
        label: Achternaam
    - legend: <h2>Heading H2</h2>
      groups:
      - id: invoer-veld-1
        inputType: input
        type: text
        label: Voornaam
      - id: invoer-veld-2
        inputType: input
        type: text
        label: Achternaam
    - legend: <h3>Heading H3</h3>
      groups:
      - id: invoer-veld-1
        inputType: input
        type: text
        label: Voornaam
      - id: invoer-veld-2
        inputType: input
        type: text
        label: Achternaam
    - legend: <h4>Heading H4</h4>
      groups:
      - id: invoer-veld-1
        inputType: input
        type: text
        label: Voornaam
      - id: invoer-veld-2
        inputType: input
        type: text
        label: Achternaam
    - legend: <h5>Heading H5</h5>
      groups:
      - id: invoer-veld-1
        inputType: input
        type: text
        label: Voornaam
      - id: invoer-veld-2
        inputType: input
        type: text
        label: Achternaam
    - legend: <h6>Heading H6</h6>
      groups:
      - id: invoer-veld-1
        inputType: input
        type: text
        label: Voornaam
      - id: invoer-veld-2
        inputType: input
        type: text
        label: Achternaam
    buttons:
    - type: submit
      modifier: dso-primary
      label: Primaire actie
    - type: button
      modifier: dso-tertiary
      label: Secondaire actie
```

https://dso-toolkit.nl/46.0.0/components/detail/form.html

## Form Buttons template

```html
    <form class="dso-single-page">
      <div class="dso-form-buttons">
        {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Primaire actie'} %}
        {% render '@button', {type: 'button', modifier: 'dso-tertiary btn-align', label: 'Link button'} %}
        </div>
      </form>
  </div>

<div class="row">
  <div class="col-md-12">
    <div class="dso-rich-content" style="margin-bottom: 24px; margin-top: 40px;">
      <h2>Button combinaties</h2>
      <p>
        Wanneer buttons bij elkaar gegroepeerd moeten worden aangeboden, moet een <code>.dso-form-buttons</code> worden toegepast.
        Doorgaans zullen deze groeperingen in context van een formulier staan, maar dit is niet noodzakelijk.
      </p>
      <p>
        Als buttons links uitgelijnd moeten worden, worden deze gegroepeerd in een <code>div.dso-aside</code>.
        Uitzondering: dit is niet nodig in een <code>.dso-single-page</code>, daar worden de knoppen al links uitgelijnd.
      </p>
    </div>
  </div>
  <div class="col-md-12">
    <h3 class="toolkit-example-label">Paginering door stappen</h3>
    <form>
      <div class="dso-form-buttons">
        <div class="dso-aside">
          {% render '@button', {type: 'button', modifier: 'dso-tertiary', label: 'Vorige stap', icon: 'chevron-left'} %}
        </div>
        {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Volgende stap', iconAfter: 'chevron-right'} %}
      </div>
    </form>
    <br>
    <h3 class="toolkit-example-label">Paginering door stappen met extra tertiaire button</h3>
    <form>
      <div class="dso-form-buttons">
        <div class="dso-aside">
          {% render '@button', {type: 'button', modifier: 'dso-tertiary', label: 'Vorige stap', icon: 'chevron-left'} %}
        </div>
        {% render '@button', {type: 'button', modifier: 'dso-tertiary btn-align', label: 'Link button'} %}
        {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Volgende stap', iconAfter: 'chevron-right'} %}
      </div>
    </form>
    <br>
    <h3 class="toolkit-example-label">Met extra tertiaire button</h3>
    <form>
      <div class="dso-form-buttons">
        {% render '@button', {type: 'button', modifier: 'dso-tertiary btn-align', label: 'Link button'} %}
        {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Volgende stap', iconAfter: 'chevron-right'} %}
      </div>
    </form>
    <br>
    <h3 class="toolkit-example-label">Met secundaire button</h3>
    <form>
      <div class="dso-form-buttons">
        {% render '@button', {type: 'button', modifier: 'dso-secondary', label: 'Standaard button'} %}
        {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Volgende stap', iconAfter: 'chevron-right'} %}
      </div>
    </form>
    <br>
    <h3 class="toolkit-example-label">Uitzondering: single page (<code>.dso-single-page</code>)</h3>
    <form class="dso-single-page">
      <div class="dso-form-buttons">
        {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Primaire actie'} %}
        {% render '@button', {type: 'button', modifier: 'dso-tertiary btn-align', label: 'Link button'} %}
      </div>
    </form>
    <br>
    <h3 class="toolkit-example-label">Uitzondering: single page (<code>.dso-single-page</code>), met secundaire button</h3>
    <form class="dso-single-page">
      <div class="dso-form-buttons">
        {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Primaire actie'} %}
        {% render '@button', {type: 'button', modifier: 'dso-secondary', label: 'Standaard button'} %}
      </div>
    </form>
    <br>
    <h3 class="toolkit-example-label">Buiten formulier context, met single page (<code>.dso-single-page</code>)</h3>
    <div class="dso-form-buttons dso-single-page">
      {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Primaire actie'} %}
      {% render '@button', {type: 'button', modifier: 'dso-tertiary btn-align', label: 'Link button'} %}
    </div>
    <br>
    <h3 class="toolkit-example-label">Buiten formulier context, met single page (<code>.dso-single-page</code>), met secundaire button</h3>
    <div class="dso-form-buttons dso-single-page">
      {% render '@button', {type: 'button', modifier: 'dso-primary', label: 'Primaire actie'} %}
      {% render '@button', {type: 'button', modifier: 'dso-secondary', label: 'Standaard button'} %}
    </div>
  </div>
```
