### ISSUE TITLE
Build: Custom property met toolkit versie

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2184]
Zodat we tijdens het debuggen van applicaties kunnen zien welke toolkit versie er actief is.

```css
:root {
  --dso-toolkit-version: 50.0.0;
}
```

Of op `html`, of `body`. Geen voorkeur (nog).

Dit moet dus tijdens het builden in de CSS terecht komt. Het lijkt erop alsof Sass geen ondersteuning heeft voor het zetten van variables tijdens het aanroepen. Misschien kunnen we een SCSS stylesheet genereren?

```scss
// generated.scss
$version: "50.0.0"; // quotes zijn nodig

// dso.scss
@use "generated";

:root {
  --dso-toolkit-version: #{$generated.version};
}

// dso.css
:root {
  --dso-toolkit-version: 50.0.0; /* wordt zonder quotes gerendered */
}
```

Het lijkt mij dat deze routines in `packages/dso-toolkit` moeten. Nog uitzoeken waar de versie vandaan komt, ik denk dat we dezelfde slugify routines moeten gebruiken voor het maken van branch releases naar dso-toolkit.nl
