### ISSUE TITLE
Fundament: Systeem voor verticaal ritme

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2217]
# Doel

Op dit moment zijn componenten verantwoordelijk voor het creeeren van ruimte. In dit issue willen we alle ruimtes tussen componenten centraliseren in één systeem.

# Oplossingsrichtingen

SCSS:

```scss
$spaced-elements: p, blockquote, table, img, hr, pre, article, aside, ul, ol, dl, h1, h2, h3, h4, h5, h6,
  figure, picture, form, fieldset, button, details, video, audio, canvas, section;
$vertical-spacing: units.$u1;

:where(#{$spaced-elements}) {
  margin-block: 0;

  & + & {
    margin-block-start: $vertical-spacing;
  }
}
```

CSS:

```css
:where(p, blockquote, table, img, hr, pre, article, aside, ul, ol, dl, h1, h2, h3, h4, h5, h6, figure, picture, form, fieldset, button, details, video, audio, canvas, section) {
  margin-block: 0;
}

:where(p, blockquote, table, img, hr, pre, article, aside, ul, ol, dl, h1, h2, h3, h4, h5, h6, figure, picture, form, fieldset, button, details, video, audio, canvas, section) + :where(p, blockquote, table, img, hr, pre, article, aside, ul, ol, dl, h1, h2, h3, h4, h5, h6, figure, picture, form, fieldset, button, details, video, audio, canvas, section) {
  margin-block-start: var(--default-spacing);
}
```

Lijst van elementen in `$spaced-elements` naar believen in te richten.

Meerdere smaken -> meerdere lijsten en meerdere afstanden. Inventariseren!
Sowieso aparte lijsten:
- types (p, , ul, ol...)
- custom (dso-*)
- classes

- [ ] https://github.com/dso-toolkit/dso-toolkit/pull/2382/files#diff-7bd39554ff376cd66211bae1dd7a0252be403e29b3f0c1360389fcc4f1e62d41R193
- [ ] Kijken naar https://github.com/dso-toolkit/dso-toolkit/issues/2211
