### ISSUE TITLE
Plaat in .dso-rich-content in het midden positioneren

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#242]
Zie https://github.com/dso-toolkit/dso-toolkit/issues/203#issuecomment-440327508 voor de achtergrond

Concreet:
```html
<div class="dso-rich-content">
  <p>Paragraaf</p>
  <p><img /></p>
  <p>Volgende paragraaf</p>
</div>
```

```css
.dso-rich-content > p > img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  max-width: 100%;
}
```
