### ISSUE TITLE
Document Component: Ondersteuning lijstnummers IMRO documenten

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2500]
De toolkit zet styling waardoor unordered lists geen list style hebben:

```css
.dso-document-components ul {
  list-style: none;
}
```
Dit doen we omdat een onderdeel van een document (voor Omgevingsdocumenten noemen we dat Document Componenten, voor IHR documenten weet ik niet hoe het heet) in een lijst wordt gezet.

De styling moet specifiek voor lijsten van Document Componenten worden gemaakt.

_Bovenstaande tekst is door @tfrijsewijk geschreven._
