### ISSUE TITLE
Styling dankuwel pagina indienen

### ISSUE THREAD

**Issue by jeroenpeeters** [dso-toolkit/dso-toolkit#260]
Tijdens het ontwikkelen van de 'dankuwel' pagina voor indienen kwam ik de volgende UI componenten tegen in het ontwerp die niet voorzien zijn in de toolkit. Op dit moment heb ik daar eigen CSS voor moeten toevoegen. Graag halen we dat er in de toekomst weer uit wanneer deze elementen in de toolkit zijn opgenomen.

Hieronder het ontwerp van de pagina:
![32_pro_dank voor uw aanvraag](https://user-images.githubusercontent.com/2640634/51180087-ab1eed00-18c7-11e9-8fbe-3cb29b4d2b05.jpg)

Hieronder een screenshot met annotatie van missende componenten.
![verzoek-indienen-goed](https://user-images.githubusercontent.com/2640634/51180125-c8ec5200-18c7-11e9-9f7e-b59b0e089b04.jpeg)

Voor jullie begrip voeg ik ook een screenshot toe van het geval wanneer een verzoek fout gaat, er missen daar opzich geen extra UI componenten.
![verzoek-indienen-fout](https://user-images.githubusercontent.com/2640634/51180148-e28d9980-18c7-11e9-94c0-a3a0eb496c7b.jpeg)

Wat ik dus mis is:
- Tabel van ingediend verzoek (zie screenshot + design)
- Los V-icoon of icoon + header

Hieronder volgt de custom CSS die ik heb moeten toevoegen, wellicht kan dit hergebruikt worden:

```css
.success-page .success-icon {
    position: relative;
    padding-left: 42px;
    line-height: 1.5;
}
.success-page .success-icon::before {
    height: 32px;
    width: 32px;
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg width='32' height='32' viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3ENotification/Succes_32x32%3C/title%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Crect fill='%2379B829' width='32' height='32' rx='16'/%3E%3Cpath d='M11 16.5l3 3 7-7' stroke='%23FFF' stroke-linecap='round' stroke-linejoin='round' stroke-width='2'/%3E%3C/g%3E%3C/svg%3E");
    content: "";
    display: block;
    position: absolute;
    left: 0px;
}
.success-page button.btn-nav {
    float: right;
}
.success-page table.permit {
    width: 100%;
    line-height: 2;
}
.success-page table.permit td {
    vertical-align: top;
}
.success-page table.permit td:first-child {
    width: 300px;
}
.success-page table.permit strong {
   color: #39870D;
}
.success-page table.permit ul {
    list-style-type: none;
    padding-left: 0;
    margin: 0;
}
.success-page .action-button {
    margin-bottom: 45px;
}
.success-page .action-button::after {
    content: " ";
    display: block;
    height: 0;
    clear: both;
}
```
