### ISSUE TITLE
Modal: Vanishes below 768px viewport

### ISSUE THREAD

**Issue by WidoBurg** [dso-toolkit/dso-toolkit#2610]
int12
Mijn Omgevingsloket -> Nieuw project (een instantie van een toolkit Dso-Modal)
Met 768 wel zichtbaar, bij 767 niet.

Bij geen modal zijn er geen issues.  

Is het een issue met een media query? 

Of verkeerd gebruik van container? We hebben er wel een paar staan, zie screenshots. . Volgens de dso-toolkit dient hij alleen bij de body (https://dso-toolkit.nl/62.18.0/fundament/layout#grid) te staan.

<img width="1697" alt="niet zichtbaar" src="https://github.com/dso-toolkit/dso-toolkit/assets/8705247/85d91d45-650c-4f57-852a-4626b684b0fa">
<img width="1709" alt="zichtbaar" src="https://github.com/dso-toolkit/dso-toolkit/assets/8705247/cea547d8-5b0f-41f1-ac08-d4a23f6f6492">

**Comment by tfrijsewijk** [comment]
In de toolkit ook te reproduceren: https://storybook.dso-toolkit.nl/62.18.0/?path=/story/voorbeeldpagina-s-patronen-modal-return-focus--modal-return-focus Open de Modal en verklein het canvas

**Comment by hansgrimm** [comment]
Dit is heel raar. Ik zie best wel veerschillen in (generated) markup met de core/modal in storybook, met name een extra #top-layer vermelding bovenin die ik niet kan thuisbrengen:
![Scherm­afbeelding 2024-04-10 om 10 01 58 (2)](https://github.com/dso-toolkit/dso-toolkit/assets/506527/2f57f6b0-705f-445a-b93a-b4c3282d16b2)

**Comment by hansgrimm** [comment]
Videootje van wat er gebeurt. de elementnaam 'knippert' ook (maar verandert zo te zien niet), en die extra `#top-layer` komt en gaat.
een raadsel.
klopt deze implementatie in de voorbeeldpagina wel?
https://github.com/dso-toolkit/dso-toolkit/assets/506527/a7a567fa-e557-4287-9b1f-6b4d37691ad5

**Comment by tfrijsewijk** [comment]
@hansgrimm Ik heb het gevonden:

In https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/modal/modal.tsx#L80 wordt de class `dso-modal-open` op body gezet waarmee de volgende styling actief wordt:

```scss
body.dso-modal-open {
  @media screen and (min-width: media-query-breakpoints.$screen-sm-min) {
    overflow: hidden;
  }

  @media screen and (max-width: media-query-breakpoints.$screen-xs-max) {
    .container,
    dso-banner,
    .dso-banner {
      display: none;
    }
  }
}
```

Ik kan mij niet herinneren waarom deze styling nodig was. Morgen verder op onderzoek.

**Comment by hansgrimm** [comment]
Wow, good catch. Het was mij ook al opgevallen dat de 'afvuurknop' van de modal ook verdween bij < 768px.

**Comment by tfrijsewijk** [comment]
Op smalle weergave wordt de Modal schermvullend:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/23a99bed-404c-44fb-80d1-9c11c6d0347e)

Kunnen we hier niet een slimmere oplossing voor maken, sinds we gebruik maken van `<dialog>` ?

**Comment by hansgrimm** [comment]
> @hansgrimm Ik heb het gevonden:
> 
> In https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/modal/modal.tsx#L80 wordt de class `dso-modal-open` op body gezet waarmee de volgende styling actief wordt:
> 
> ```css-scss
> body.dso-modal-open {
>   @media screen and (min-width: media-query-breakpoints.$screen-sm-min) {
>     overflow: hidden;
>   }
> 
>   @media screen and (max-width: media-query-breakpoints.$screen-xs-max) {
>     .container,
>     dso-banner,
>     .dso-banner {
>       display: none;
>     }
>   }
> }
> ```
> 
> Ik kan mij niet herinneren waarom deze styling nodig was. Morgen verder op onderzoek.

Oplossing nu: 

```scss
body:has(dialog[open]),
body:has(dso-modal.hydrated) {
  overflow: hidden;
}
```
