### ISSUE TITLE
Sass: Deprecation warning mixed declarations

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2724]
In #2686 is `sass` van `^1.77.4` naar `^1.77.7` geüpdatet. In versie `1.77.7` is de volgende DEPRECATION WARNING ten tonele verschenen:

```
DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls
``` 
Wanneer sass met option `verbose: true` wordt gecompileerd dan worden de 192 DEPRECATION WARNINGs gelist in de output van `yarn start` en `yarn build`. De option `verbose: true` kan in dso-toolkit/gulp/transformers/sass-transformer.js na r/14 worden toegevoegd.

**Comment by iterox** [comment]
Voeg `verbose: true,` toe aan de `options` in `compileString` in `sass.transfromer.js` om alle deprecation-warning te detecteren

**Comment by hansgrimm** [comment]
Het gaat om selectors die naar mijn eigen maatstaven een beetje rommelig zijn opgebouwd:
```scss

.selector {
    property: value;
    property: value;

    a {
        property: value;
    }

    property: value; // <-- deze had eigenlijk hierboven gemoeten in mijn wereld.
}
```
Dat gezegd hebbende, zoiets kan ook heel makkelijk dmv een mixin of (god forbid) een extend, die achterin geplaatst wordt.
Voorheen ruimde Sass dat allemaal keurig op, maar dat gaat veranderen.

Kwestie van alle 192 foutmeldingen langslopen en de boel aanpassen.

**Comment by tfrijsewijk** [comment]
> Het gaat om selectors die naar mijn eigen maatstaven een beetje rommelig zijn opgebouwd:
> 
> .selector {
>     property: value;
>     property: value;
> 
>     a {
>         property: value;
>     }
> 
>     property: value; // <-- deze had eigenlijk hierboven gemoeten in mijn wereld.
> }

Mee eens. Maar ik vraag mij af of je deze situatie uberhaupt bent tegengekomen, en als dat zo is: dit is makkelijk te fixen.

Het gaat om de volgende situaties:

```scss
@mixin component() {
  color: red;

  a {
    border-block: 1px;
  }
}

.component {
  @include component();

  color: blue;
}
```
_https://sass-lang.com/playground/#eJxNjDEKwCAQBPt7xZVJkYCtNn4l6hUS9UQiCMG/RySElDPsjhA6+uYTWo6ZE6VrWfEGHBy4SCzkFAw8pkQ0XByVzQS2p0SRmxq6QwfYv8Kcap9sqI7+4Vl6wyZUUuP3AABVJ0o=?s=L1C1-L14C1_

Hier willen we de default color property overriden. De uiteindelijke CSS is:

```css
.component {
  color: red;
  color: blue;
}
.component a {
  border-block: 1px;
}
```

`blue` komt na `red ✅ 

Als we doen wat jij voorstelt, de property vóór de mixin zetten krijgen we dit:

```css
.component {
  color: blue;
  color: red;
}
.component a {
  border-block: 1px;
}
```

`blue` komt vóór `red` ❌ 

De voorgestelde (tijdelijke) fix van Sass is `& {}`:

```scss
@mixin component() {
  color: red;

  a {
    border-block: 1px;
  }
}

.component {
  @include component();

  & {
    color: blue;
  }
}
```
_https://sass-lang.com/playground/#eJwzNHTIzazIzFNIzs8tyM9LzSvR0FSo5lIA8nPyi6wUilJTrLmA3ESwoIJCUn5RSmqRblJOfnK2lYJhQYU1ULiWq5aLSw9uAlipQ2Zeck5pSiqywWCT1KAmQS1IyilNhZkBANC/KVw=_


Resulteert in:

```css
.component {
  color: red;
}
.component a {
  border-block: 1px;
}
.component {
  color: blue;
}
```

`blue` komt na `red` ✅ 

De `& {}` truuk is een tijdelijke situatie. Zonder deze truuk gaat Sass binnenkort ook deze CSS genereren.

Gezien de omvang van deze change (193 occurances) wil ik ook niet wachten tot Sass dit gedrag gaat afdwingen. Dan kunnen we pas updaten als we de impact helder hebben.

Ik stel voor dat in dit issue de impact analyse maken:
* We zetten de stylelint regel `no-duplicate-selectors` uit.
* Overal waar Sass klaagt zetten we `& {}` omheen.

En vanaf hier pakken we het op.

@iterox @hansgrimm wat denken jullie?
