### ISSUE TITLE
Conclusie component

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#282]
@MichielDHVD @tfrijsewijk 

Wij zijn de conclusie voor de vergunningscheck aan het uitbreiden, zie schermontwerp hieronder.

![00a basis met alles - iconen](https://user-images.githubusercontent.com/18580063/53406799-ffcf8080-39ba-11e9-92c9-845cf509872f.png)

Wat we missen is een component/styling voor de conclusies. Dit zou een unordered list moeten zijn met een aantal classes om de juiste iconen te tonen, afhankelijk van het type conclusie.

Voor nu heb ik het als volgt opgelost, met custom css in onze applicatie, maar we zouden dit graag uit de toolkit willen halen, zodat deze css weg kan. 

Het onderste heeft te maken met de uitlijning van de toelichting, zie: "Oprit aanleggen".

```css
/* Missing styling in DSO-Toolkit for checken conclusion page */

ul.conclusion {
    list-style-type: none;
    padding-left: 0;
    margin: 4px 0 0 0;
}

ul.conclusion li {
    background-repeat: no-repeat;
    background-position: left 3px;
    background-size: 18px;
    padding-left: 26px;
}

ul.conclusion li:last-child {
    margin: 0 0 16px 0;
}

ul.conclusion li.warning {
    background-image: url("data:image/svg+xml,%3Csvg width='32' height='32' viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3ENotification/Warning_32x32%3C/title%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Crect fill='%23DCD500' width='32' height='32' rx='16'/%3E%3Cg transform='translate(10 10)'%3E%3Cpath d='M6 1v5' stroke='%23000' stroke-width='2' stroke-linecap='round'/%3E%3Ccircle fill='%23000' cx='6' cy='10.5' r='1.5'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
}

ul.conclusion li.success {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg width='32' height='32' viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3ENotification/Succes_32x32%3C/title%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Crect fill='%2379B829' width='32' height='32' rx='16'/%3E%3Cpath d='M11 16.5l3 3 7-7' stroke='%23FFF' stroke-linecap='round' stroke-linejoin='round' stroke-width='2'/%3E%3C/g%3E%3C/svg%3E");
}

ul.conclusion li.forbidden {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg width='32' height='32' viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg' %3E%3Cpath fill='%23ce3f51' d='M256 8C119.034 8 8 119.033 8 256s111.034 248 248 248 248-111.034 248-248S392.967 8 256 8zm130.108 117.892c65.448 65.448 70 165.481 20.677 235.637L150.47 105.216c70.204-49.356 170.226-44.735 235.638 20.676zM125.892 386.108c-65.448-65.448-70-165.481-20.677-235.637L361.53 406.784c-70.203 49.356-170.226 44.736-235.638-20.676z' class=''%3E%3C/path%3E%3C/svg%3E");
}

ul.conclusion li ul li {
    padding: 0;
    font-style: italic;
}

ul.conclusion .dso-field-info {
    margin: 16px 0 16px -26px;
}`

**Comment by TonD83** [comment]
In overleg met @MichielDHVD wat aan de spacing gedaan, bijgewerkte CSS die we voor nu gebruiken:

```css
/* Missing styling in DSO-Toolkit for checken conclusion page */

ul.conclusion {
    list-style-type: none;
    padding-left: 0;
    margin: 4px 0 0 0;
}

ul.conclusion li {
    background-repeat: no-repeat;
    background-position: left 3px;
    background-size: 18px;
    padding-left: 26px;
    margin: 0 0 8px 0;
}

ul.conclusion li.warning {
    background-image: url("data:image/svg+xml,%3Csvg width='32' height='32' viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3ENotification/Warning_32x32%3C/title%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Crect fill='%23DCD500' width='32' height='32' rx='16'/%3E%3Cg transform='translate(10 10)'%3E%3Cpath d='M6 1v5' stroke='%23000' stroke-width='2' stroke-linecap='round'/%3E%3Ccircle fill='%23000' cx='6' cy='10.5' r='1.5'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
}

ul.conclusion li.success {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg width='32' height='32' viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3ENotification/Succes_32x32%3C/title%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Crect fill='%2379B829' width='32' height='32' rx='16'/%3E%3Cpath d='M11 16.5l3 3 7-7' stroke='%23FFF' stroke-linecap='round' stroke-linejoin='round' stroke-width='2'/%3E%3C/g%3E%3C/svg%3E");
}

ul.conclusion li.forbidden {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg width='32' height='32' viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg' %3E%3Cpath fill='%23ce3f51' d='M256 8C119.034 8 8 119.033 8 256s111.034 248 248 248 248-111.034 248-248S392.967 8 256 8zm130.108 117.892c65.448 65.448 70 165.481 20.677 235.637L150.47 105.216c70.204-49.356 170.226-44.735 235.638 20.676zM125.892 386.108c-65.448-65.448-70-165.481-20.677-235.637L361.53 406.784c-70.203 49.356-170.226 44.736-235.638-20.676z' class=''%3E%3C/path%3E%3C/svg%3E");
}

ul.conclusion li ul li {
    padding: 0;
    font-style: italic;
    margin: 0 0 8px 0;
}

ul.conclusion .dso-field-info {
    margin: 16px 0 16px -26px;
}
```
