### ISSUE TITLE
Card: Internalize webcomponent styling

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2828]
Het Card component maakt gebruik van deze styling

```SCSS
&[is-selectable] {
```

Dit moeten we ombouwen naar `::slotted` en `::part` selectors.

_Originally posted by @tfrijsewijk in https://github.com/dso-toolkit/dso-toolkit/pull/2826#discussion_r1785121179_

**Comment by hansgrimm** [comment]
Ik ben voor zover ik weet geen onderdeel geweest van deze discussie, dus wat is de ratio van deze ingreep? Ik weet dat `::slotted` flink wat nadelen heeft (geen children, `!important` nodig). Met `::part` heb ik nog niet genoeg ervaring, dus dat moet nog blijken.

Maar ik vraag me vooral waarom we dit zo graag willen. Voor mij zijn de `::slotted` en `::part` selectors nog een beetje een "if all else fails"-oplossing ;)

**Comment by tfrijsewijk** [comment]
Goed idee om 'm donderdag te behandelen. Om je vast wat achtergrond informatie te geven:

Op dit moment leeft de styling voor de Web Component implementatie van Card op twee plekken:
* dso.css: via een `dso.scss` met een `@use "components/src/card.scss`
* Een "constructed stylesheet" in het Web Component via de Sass stylesheet `packages/core/src/components/card/card.scss`.

Dit resulteert in:

* Slechte herbruikbaarheid: Als we Card ooit in een andere shadow root willen gebruiken, moeten we ook de Sass stylesheet importeren
* De Web Component implementatie en HTML/CSS implementatie zitten in `packages/dso-toolkit/src/components/card/card.scss`, terwijl in `dso-toolkit` alleen de HTML/CSS implementaties en Sass mixins horen
* Het Web Component is niet zelfstandig. Zonder `dso.css` werkt de Web Component implementatie van  Card niet naar behoren.

Door de Web Component-gerelateerde styling uit `packages/dso-toolkit/src/components/card/card.scss` te verplaatsen naar `packages/core/src/components/card/card.scss` en op `::slotted` (en misschien `::part`) selectors te plaatsen:

* is het component herbruikbaar in andere shadow roots
* is er geen styling voor het Web Component meer aanwezig in `dso-toolkit`
* is het Web Component zelfstandig. Zonder `dso.css` werkt het component ook.

Kauw er vast op, donderdag hebben we het er verder over.

**Comment by hansgrimm** [comment]
Check. Ik ben alvast begonnen met wat css te kloppen. Ik ga ervan uit dat alle styling die vanuit `dso.css` komt moet worden opgenomen in de constructed stylesheet.

- geldt dat ook voor de base styles die nu op `body` staan, zoals `font-family` e.d.?
- `--dso-toolkit-version` is binnen het webcomponent nu `undefined`. moeten we daar wat mee?
![Image](https://github.com/user-attachments/assets/749b90b7-df0b-4ab0-9acd-ee1bc9854baa)
^^ voer voor de refinement :)

**Comment by tfrijsewijk** [comment]
Definition List HTML/CSS implementatie ter inspiratie voor de CSS custom properties.

**Comment by hansgrimm** [comment]
https://github.com/WICG/webcomponents/issues/594

**Comment by hansgrimm** [comment]
> Definition List HTML/CSS implementatie ter inspiratie voor de CSS custom properties.

Check, maar in deze issue gaat het erom dat we de hele styling van een webcomponent (inclusief de slots) onafhankelijk maken van dso.css; daarom moeten zowel de properties als de values van binnenuit gezet worden, niet alleen de values. die methode gaat hier dus niet werken. Ik word ernstig dwarsgezeten door de onmogelijkheid om kinderen van `::slotted` te selecteren, en blijf dus met een paar dingen zitten die ik niet over kan zetten, zoals:
```scss
.dso-card-interactions,
[slot="interactions"],
[slot="interaction"] {
  display: flex;
  justify-content: space-between;
  margin-inline-start: auto;

  .dso-card-interaction {
    align-items: center;
    display: flex;
    text-align: center;

    p {
      margin-block-end: 0;
    }
  }

  .dso-info-button {
    margin: 0;
  }

  @media screen and (max-width: media-query-breakpoints.$screen-xs-min) {
    flex-basis: 100%;
    margin-block-start: units.$u2;
  }
}
```
