### ISSUE TITLE
Plaat in toelichting buiten formulier niet meer in het midden gepositioneerd

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#291]
Zie #242 en #250 en commit https://github.com/dso-toolkit/dso-toolkit/commit/590f1b94465b92df32307d892a1a185ad75ed903

Helaas staat de plaat nu niet meer in het midden, omdat de toelichtingenbox niet in een form zit.

**Comment by tfrijsewijk** [comment]
Volgens mij heb je gelijk. In het MR #251 heb ik niet mijn eigen oplossing zoals ik die in #250 omschrijf uitgevoerd..

>Oplossing: De betreffende CSS die voor #242 is gemaakt verder scopen tot de toelichtingen box.

Ik heb wat styling opgeschoven, maar de selector moest heel anders worden:

```scss
.dso-info img {
  display: block;
  margin: $u1 auto;
  max-width: 100%;
}
```

Wat dacht je hier van?
