### ISSUE TITLE
Document Header: Varianten voor besluitversies

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#3193]
## Omschrijving van de wijziging

In de documentheader willen we het onderscheid tussen een vastgesteld, een besluitversie en een ontwerpversie wat duidelijker maken. Daarnaast wordt nu gebruik gemaakt van het Advanced select component met daarin 2 indicatoren. De indicatoren zijn niet toegankelijk.  

De wijzigingen zijn het 2 varianten toevoegen met bovenin een statusbalk: besluitversie en ontwerpversie

---

## Kaders van de wijziging

Document Header

---

## Ontwerp

<img width="860" height="429" alt="Image" src="https://github.com/user-attachments/assets/b47e92b6-3f7c-48a0-b014-e89360abfcc0" />

 
- **Ontwerp in Figma**: pagina - document header

## Toelichting Ontwerp
- 3 Varianten van de documentheader (Document Status: Vastgesteld/Default, Ontwerp en Besluit ) 
- De twee besluitvarianten hebben een statusbalk. De Status Message daarin is aanpasbaar door de afnemer.
- Het slot onder documentkenmerken is bedoeld om te vullen met definition lists en tussenkopjes. (zie patterns)
- In Sticky state is de gehele balk aanklikbaar (om te fungeren als "scroll up" knop)  

---

## Toegankelijkheid

_Controleer of de wijziging voldoet aan de toegankelijkheidseisen (WCAG 2.1 of hoger)._

---

## Impactanalyse

**Breaking change?**: Ja/nee. _Indien ja, beschrijf de impact en wat er nodig is voor een migratie._

---

## Wijzigingen aan het Component Model

_Geef aan of de wijziging invloed heeft op het Component Model en licht dit toe._

```ts
interface PropertyModel {}

interface ComponentModel {
  nieuweProperty: PropertyModel;
}
```

---

## Overige opmerkingen

Idee ter inspiratie voor het zetten van de achtergroundkleur op de button.

```scss
// button.component.scss
button {
  --_dso-button-background-color: #{$dso-button-background-color};

  background-color: var(--_dso-button-background-color);
}

// document-header.component.scss
.dso-document-header.dso-besluitversie {
  button {
    --_dso-button-background-color: #{$document-header-background-color};
  }
}
```

```

## Checklist

- [ ] Omschrijving van de wijziging
- [ ] Kaders van de wijziging
- [ ] Ontwerp
- [ ] Toegankelijkheid
- [ ] Impactanalyse
- [ ] Wijzigingen aan het Component Model
- [ ] Overige opmerkingen
