### ISSUE TITLE
Focus State: Uniforme focus styling

### ISSUE THREAD

**Issue by cvanderleij-ilionx** [dso-toolkit/dso-toolkit#3228]
## Omschrijving van de taak

Inventariseren van alle (interactieve) componenten met custom focus styling, of waar de browser native focus styling wordt onderdrukt.

In de basis is dat iets met `:focus`, `:focus-visible` en de `outline` CSS property.

Deze custom focus styling in lijn brengen met de regel "geen custom focus styling", ofwel omzetten naar de standaard: offset 4px en zwarte kleur.

Aandachtspunt is focusbare elementen in een shadow root.

**Comment by iterox** [comment]
Modal

modal.mixins.scss
```scss
.dso-body {
  &:focus-visible {
    outline: none;
  }
}
```

**Comment by iterox** [comment]
List Button

list-button.scss

```scss
@mixin _state-styling($background-color: inherit, $border-color: inherit, $color: inherit) {
  & {
    background-color: $background-color;
    border-color: $border-color;
    color: $color;
  }
}
...
.dso-button-group {
  ...
  > *:hover + .dso-input-number,
  > *:focus + .dso-input-number {
    @include _state-styling(colors.$wit, button.$secondary-hover-background-color, colors.$grijs-90);
  }
  ...
.dso-list-button {
  ...
  &:hover,
  &:focus {
    @include _state-styling(colors.$wit, button.$secondary-border-color, colors.$grijs-90);
  }
  ...
```

**Comment by iterox** [comment]
Logo

logo.scss

```scss
.logo-url,
.logo-label-url {
  ...

  &,
  &:hover,
  &:focus,
  &:visited {
    color: colors.$bosgroen;
  }
  ...
```

**Comment by iterox** [comment]
Selectable

selectable.scss

```scss
  ...
  input[type="checkbox"][disabled],
  input[type="radio"][disabled] {
    &,
    &:active,
    &:focus {
      + label {
        &::before {
          background-color: colors.$wit;
          box-shadow: 0 0 0 selectable-variables.$border-width selectable-variables.$disabled-color;
        }
       ...
.dso-selectable-container {
  ...

  .dso-selectable-input-wrapper {
    ...

    input[type="radio"],
    input[type="checkbox"] {
      &:focus + label::before {
        box-shadow: 0 0 0 selectable-variables.$border-width
          var(--dso-selectable-color, selectable-variables.$valid-color);
        block-size: selectable-variables.$size - 2 * selectable-variables.$border-width;
        inset-inline-start: selectable-variables.$border-width;
        inset-block-start: selectable-variables.$border-width;
        inline-size: selectable-variables.$size - 2 * selectable-variables.$border-width;
      }
    ...
```
Gerelateerd aan #3094 List Button: betere zichtbare focusstate

**Comment by iterox** [comment]
Tree View

tree-view.scss

```scss
...
.tree-content {
  ...
  a {
    ...
    &:hover,
    &:focus {
      color: scaffolding.$text-color;
      text-decoration: none;
    }
  ...
    &.selected {
      ...
      &:hover,
      &:focus {
        text-decoration: none;
      }
    }
  ...
  &.active {
    ...

    &:hover,
    &:focus {
      text-decoration: none;
    }
  ...
  a {
    color: colors.$mauve;

    &:hover,
    &:focus {
      text-decoration: none;
    }
  }
  ...
```

**Comment by iterox** [comment]
Viewer Grid

viewer-grid.scss

```scss
.sizing-buttons,
.toggle-button {
  ...
  button {
    ...
  &:focus-visible {
        outline-offset: -1px;
      }
    }
  }
...
```
